map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

map ctrl+shift+t new_tab_with_cwd

# Cursor navigation
# Jump to end of line
map ctrl+shift+right send_text all \x05
map ctrl+shift+left send_text all \x01

# Jump to prev/next word
map ctrl+right send_text all \x1b\x66
map ctrl+left send_text all \x1b\x62

# Delete line from cursor position to start of line:
map ctrl+shift+backspace send_text all \x15
